// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/message.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	protobuf/message.proto

It has these top-level messages:
	Simple
	Feature
	Player
	GameInfo
	GameRank
	PlayerRank
	Distance
	Detection
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Simple struct {
	EventName        *string `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Simple) Reset()                    { *m = Simple{} }
func (m *Simple) String() string            { return proto.CompactTextString(m) }
func (*Simple) ProtoMessage()               {}
func (*Simple) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Simple) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Simple) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type Feature struct {
	EventName        *string `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Group            *string `protobuf:"bytes,2,req,name=group" json:"group,omitempty"`
	Id               *string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Coords           *string `protobuf:"bytes,4,opt,name=coords" json:"coords,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Feature) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Feature) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *Feature) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Feature) GetCoords() string {
	if m != nil && m.Coords != nil {
		return *m.Coords
	}
	return ""
}

type Player struct {
	EventName        *string  `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string  `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Lon              *float64 `protobuf:"fixed64,3,req,name=lon" json:"lon,omitempty"`
	Lat              *float64 `protobuf:"fixed64,4,req,name=lat" json:"lat,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Player) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Player) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Player) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func (m *Player) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

type GameInfo struct {
	EventName        *string `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Game             *string `protobuf:"bytes,2,req,name=game" json:"game,omitempty"`
	Role             *string `protobuf:"bytes,3,req,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameInfo) Reset()                    { *m = GameInfo{} }
func (m *GameInfo) String() string            { return proto.CompactTextString(m) }
func (*GameInfo) ProtoMessage()               {}
func (*GameInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GameInfo) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *GameInfo) GetGame() string {
	if m != nil && m.Game != nil {
		return *m.Game
	}
	return ""
}

func (m *GameInfo) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

type GameRank struct {
	EventName        *string       `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Game             *string       `protobuf:"bytes,2,req,name=game" json:"game,omitempty"`
	PlayersRank      []*PlayerRank `protobuf:"bytes,3,rep,name=players_rank,json=playersRank" json:"players_rank,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GameRank) Reset()                    { *m = GameRank{} }
func (m *GameRank) String() string            { return proto.CompactTextString(m) }
func (*GameRank) ProtoMessage()               {}
func (*GameRank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GameRank) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *GameRank) GetGame() string {
	if m != nil && m.Game != nil {
		return *m.Game
	}
	return ""
}

func (m *GameRank) GetPlayersRank() []*PlayerRank {
	if m != nil {
		return m.PlayersRank
	}
	return nil
}

type PlayerRank struct {
	Player           *string `protobuf:"bytes,1,req,name=player" json:"player,omitempty"`
	Points           *int32  `protobuf:"varint,2,req,name=points" json:"points,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerRank) Reset()                    { *m = PlayerRank{} }
func (m *PlayerRank) String() string            { return proto.CompactTextString(m) }
func (*PlayerRank) ProtoMessage()               {}
func (*PlayerRank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayerRank) GetPlayer() string {
	if m != nil && m.Player != nil {
		return *m.Player
	}
	return ""
}

func (m *PlayerRank) GetPoints() int32 {
	if m != nil && m.Points != nil {
		return *m.Points
	}
	return 0
}

type Distance struct {
	EventName        *string  `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Dist             *float64 `protobuf:"fixed64,2,req,name=dist" json:"dist,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Distance) Reset()                    { *m = Distance{} }
func (m *Distance) String() string            { return proto.CompactTextString(m) }
func (*Distance) ProtoMessage()               {}
func (*Distance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Distance) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Distance) GetDist() float64 {
	if m != nil && m.Dist != nil {
		return *m.Dist
	}
	return 0
}

type Detection struct {
	EventName        *string  `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	FeatId           *string  `protobuf:"bytes,2,req,name=feat_id,json=featId" json:"feat_id,omitempty"`
	Lat              *float64 `protobuf:"fixed64,3,req,name=lat" json:"lat,omitempty"`
	Lon              *float64 `protobuf:"fixed64,4,req,name=lon" json:"lon,omitempty"`
	NearByFeatId     *string  `protobuf:"bytes,5,req,name=near_by_feat_id,json=nearByFeatId" json:"near_by_feat_id,omitempty"`
	NearByMeters     *float64 `protobuf:"fixed64,6,req,name=near_by_meters,json=nearByMeters" json:"near_by_meters,omitempty"`
	Intersects       *string  `protobuf:"bytes,7,req,name=intersects" json:"intersects,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Detection) Reset()                    { *m = Detection{} }
func (m *Detection) String() string            { return proto.CompactTextString(m) }
func (*Detection) ProtoMessage()               {}
func (*Detection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Detection) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Detection) GetFeatId() string {
	if m != nil && m.FeatId != nil {
		return *m.FeatId
	}
	return ""
}

func (m *Detection) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Detection) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func (m *Detection) GetNearByFeatId() string {
	if m != nil && m.NearByFeatId != nil {
		return *m.NearByFeatId
	}
	return ""
}

func (m *Detection) GetNearByMeters() float64 {
	if m != nil && m.NearByMeters != nil {
		return *m.NearByMeters
	}
	return 0
}

func (m *Detection) GetIntersects() string {
	if m != nil && m.Intersects != nil {
		return *m.Intersects
	}
	return ""
}

func init() {
	proto.RegisterType((*Simple)(nil), "protobuf.Simple")
	proto.RegisterType((*Feature)(nil), "protobuf.Feature")
	proto.RegisterType((*Player)(nil), "protobuf.Player")
	proto.RegisterType((*GameInfo)(nil), "protobuf.GameInfo")
	proto.RegisterType((*GameRank)(nil), "protobuf.GameRank")
	proto.RegisterType((*PlayerRank)(nil), "protobuf.PlayerRank")
	proto.RegisterType((*Distance)(nil), "protobuf.Distance")
	proto.RegisterType((*Detection)(nil), "protobuf.Detection")
}

func init() { proto.RegisterFile("protobuf/message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0x87, 0x95, 0x3f, 0x9b, 0xdd, 0x4c, 0xab, 0x82, 0xa2, 0xaa, 0xf8, 0x02, 0x8a, 0x2c, 0x90,
	0xf6, 0xb4, 0x48, 0x5c, 0x7a, 0x81, 0x0b, 0xaa, 0x8a, 0x7a, 0x00, 0x41, 0x38, 0x72, 0x88, 0xdc,
	0x64, 0xb2, 0xb2, 0x9a, 0xd8, 0x91, 0xed, 0x5d, 0x69, 0xdf, 0x93, 0x07, 0x42, 0x9e, 0x38, 0xbb,
	0xdc, 0x16, 0x7a, 0x9b, 0xf9, 0x3c, 0xf9, 0xc6, 0xf1, 0x0f, 0x6e, 0x46, 0xa3, 0x9d, 0x7e, 0xdc,
	0x75, 0xef, 0x07, 0xb4, 0x56, 0x6c, 0x71, 0x43, 0xa0, 0x58, 0xcd, 0x9c, 0xdf, 0x42, 0xf6, 0x53,
	0x0e, 0x63, 0x8f, 0xc5, 0x6b, 0x00, 0xdc, 0xa3, 0x72, 0xb5, 0x12, 0x03, 0xb2, 0xa8, 0x8c, 0xd7,
	0x79, 0x95, 0x13, 0xf9, 0x26, 0x06, 0x2c, 0xae, 0x20, 0x96, 0x2d, 0x8b, 0x09, 0xc7, 0xb2, 0xe5,
	0x1d, 0x2c, 0xef, 0x51, 0xb8, 0x9d, 0x39, 0xfb, 0xe5, 0x35, 0x2c, 0xb6, 0x46, 0xef, 0xc6, 0xf0,
	0xf1, 0xd4, 0x04, 0x5f, 0x52, 0x46, 0x93, 0xaf, 0xb8, 0x81, 0xac, 0xd1, 0xda, 0xb4, 0x96, 0xa5,
	0xc4, 0x42, 0xc7, 0x7f, 0x41, 0xf6, 0xbd, 0x17, 0x07, 0x34, 0xff, 0x79, 0xc1, 0xe2, 0x25, 0x24,
	0xbd, 0x56, 0x2c, 0x29, 0xe3, 0x75, 0x54, 0xf9, 0x92, 0x88, 0x70, 0x2c, 0x0d, 0x44, 0x38, 0xfe,
	0x03, 0x56, 0x5f, 0xc4, 0x80, 0x0f, 0xaa, 0xd3, 0xe7, 0xf4, 0x05, 0xa4, 0x5b, 0x7f, 0x30, 0x2d,
	0xa0, 0xda, 0x33, 0xa3, 0x7b, 0xa4, 0x1d, 0x79, 0x45, 0x35, 0xdf, 0x4f, 0xca, 0x4a, 0xa8, 0xa7,
	0xe7, 0x28, 0x6f, 0xe1, 0x72, 0xa4, 0xdf, 0xb5, 0xb5, 0x11, 0xea, 0x89, 0x25, 0x65, 0xb2, 0xbe,
	0xf8, 0x70, 0xbd, 0x99, 0x03, 0xdb, 0x4c, 0x8f, 0xe1, 0xf5, 0xd5, 0x45, 0x98, 0xf4, 0x0d, 0xff,
	0x08, 0x70, 0x3a, 0xf2, 0xaf, 0x39, 0x1d, 0x86, 0xad, 0xa1, 0x23, 0xae, 0xa5, 0x72, 0x96, 0x96,
	0x2e, 0xaa, 0xd0, 0xf1, 0x4f, 0xb0, 0xba, 0x93, 0xd6, 0x09, 0xd5, 0xe0, 0x3f, 0xdc, 0xba, 0x95,
	0xd6, 0x91, 0x20, 0xaa, 0xa8, 0xe6, 0xbf, 0x23, 0xc8, 0xef, 0xd0, 0x61, 0xe3, 0xa4, 0x56, 0xe7,
	0x04, 0xaf, 0x60, 0xd9, 0xa1, 0x70, 0xf5, 0x31, 0xad, 0xcc, 0xb7, 0x0f, 0xed, 0x9c, 0x4f, 0x72,
	0xcc, 0x67, 0xce, 0x30, 0x3d, 0x65, 0xf8, 0x0e, 0x5e, 0x28, 0x14, 0xa6, 0x7e, 0x3c, 0xd4, 0xb3,
	0x64, 0x41, 0x92, 0x4b, 0x8f, 0x3f, 0x1f, 0xee, 0x27, 0xd5, 0x5b, 0xb8, 0x9a, 0xc7, 0x06, 0x74,
	0x68, 0x2c, 0xcb, 0xc8, 0x11, 0xa6, 0xbe, 0x12, 0x2b, 0xde, 0x00, 0x48, 0xe5, 0x2b, 0x6c, 0x9c,
	0x65, 0x4b, 0xf2, 0xfc, 0x45, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x25, 0xc4, 0x09, 0xc8, 0x3f,
	0x03, 0x00, 0x00,
}
