// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/message.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	protobuf/message.proto

It has these top-level messages:
	Simple
	Feature
	Player
	GameInfo
	GameRank
	PlayerRank
	Distance
	Detection
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Simple struct {
	EventName        *string `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Simple) Reset()                    { *m = Simple{} }
func (m *Simple) String() string            { return proto.CompactTextString(m) }
func (*Simple) ProtoMessage()               {}
func (*Simple) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Simple) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Simple) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type Feature struct {
	EventName        *string `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Group            *string `protobuf:"bytes,2,req,name=group" json:"group,omitempty"`
	Id               *string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Coords           *string `protobuf:"bytes,4,opt,name=coords" json:"coords,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Feature) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Feature) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *Feature) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Feature) GetCoords() string {
	if m != nil && m.Coords != nil {
		return *m.Coords
	}
	return ""
}

type Player struct {
	EventName        *string  `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string  `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Lon              *float64 `protobuf:"fixed64,3,req,name=lon" json:"lon,omitempty"`
	Lat              *float64 `protobuf:"fixed64,4,req,name=lat" json:"lat,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Player) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Player) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Player) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func (m *Player) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

type GameInfo struct {
	EventName        *string `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Game             *string `protobuf:"bytes,3,req,name=game" json:"game,omitempty"`
	Role             *string `protobuf:"bytes,4,req,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameInfo) Reset()                    { *m = GameInfo{} }
func (m *GameInfo) String() string            { return proto.CompactTextString(m) }
func (*GameInfo) ProtoMessage()               {}
func (*GameInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GameInfo) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *GameInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *GameInfo) GetGame() string {
	if m != nil && m.Game != nil {
		return *m.Game
	}
	return ""
}

func (m *GameInfo) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

type GameRank struct {
	EventName        *string       `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string       `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Game             *string       `protobuf:"bytes,3,req,name=game" json:"game,omitempty"`
	PlayersRank      []*PlayerRank `protobuf:"bytes,4,rep,name=players_rank,json=playersRank" json:"players_rank,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GameRank) Reset()                    { *m = GameRank{} }
func (m *GameRank) String() string            { return proto.CompactTextString(m) }
func (*GameRank) ProtoMessage()               {}
func (*GameRank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GameRank) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *GameRank) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *GameRank) GetGame() string {
	if m != nil && m.Game != nil {
		return *m.Game
	}
	return ""
}

func (m *GameRank) GetPlayersRank() []*PlayerRank {
	if m != nil {
		return m.PlayersRank
	}
	return nil
}

type PlayerRank struct {
	Player           *string `protobuf:"bytes,1,req,name=player" json:"player,omitempty"`
	Points           *int32  `protobuf:"varint,2,req,name=points" json:"points,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerRank) Reset()                    { *m = PlayerRank{} }
func (m *PlayerRank) String() string            { return proto.CompactTextString(m) }
func (*PlayerRank) ProtoMessage()               {}
func (*PlayerRank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayerRank) GetPlayer() string {
	if m != nil && m.Player != nil {
		return *m.Player
	}
	return ""
}

func (m *PlayerRank) GetPoints() int32 {
	if m != nil && m.Points != nil {
		return *m.Points
	}
	return 0
}

type Distance struct {
	EventName        *string  `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string  `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Dist             *float64 `protobuf:"fixed64,3,req,name=dist" json:"dist,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Distance) Reset()                    { *m = Distance{} }
func (m *Distance) String() string            { return proto.CompactTextString(m) }
func (*Distance) ProtoMessage()               {}
func (*Distance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Distance) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Distance) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Distance) GetDist() float64 {
	if m != nil && m.Dist != nil {
		return *m.Dist
	}
	return 0
}

type Detection struct {
	EventName        *string  `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string  `protobuf:"bytes,3,req,name=id" json:"id,omitempty"`
	FeatId           *string  `protobuf:"bytes,4,req,name=feat_id,json=featId" json:"feat_id,omitempty"`
	Lat              *float64 `protobuf:"fixed64,5,req,name=lat" json:"lat,omitempty"`
	Lon              *float64 `protobuf:"fixed64,6,req,name=lon" json:"lon,omitempty"`
	NearByFeatId     *string  `protobuf:"bytes,7,req,name=near_by_feat_id,json=nearByFeatId" json:"near_by_feat_id,omitempty"`
	NearByMeters     *float64 `protobuf:"fixed64,8,req,name=near_by_meters,json=nearByMeters" json:"near_by_meters,omitempty"`
	Intersects       *string  `protobuf:"bytes,9,req,name=intersects" json:"intersects,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Detection) Reset()                    { *m = Detection{} }
func (m *Detection) String() string            { return proto.CompactTextString(m) }
func (*Detection) ProtoMessage()               {}
func (*Detection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Detection) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Detection) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Detection) GetFeatId() string {
	if m != nil && m.FeatId != nil {
		return *m.FeatId
	}
	return ""
}

func (m *Detection) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Detection) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func (m *Detection) GetNearByFeatId() string {
	if m != nil && m.NearByFeatId != nil {
		return *m.NearByFeatId
	}
	return ""
}

func (m *Detection) GetNearByMeters() float64 {
	if m != nil && m.NearByMeters != nil {
		return *m.NearByMeters
	}
	return 0
}

func (m *Detection) GetIntersects() string {
	if m != nil && m.Intersects != nil {
		return *m.Intersects
	}
	return ""
}

func init() {
	proto.RegisterType((*Simple)(nil), "protobuf.Simple")
	proto.RegisterType((*Feature)(nil), "protobuf.Feature")
	proto.RegisterType((*Player)(nil), "protobuf.Player")
	proto.RegisterType((*GameInfo)(nil), "protobuf.GameInfo")
	proto.RegisterType((*GameRank)(nil), "protobuf.GameRank")
	proto.RegisterType((*PlayerRank)(nil), "protobuf.PlayerRank")
	proto.RegisterType((*Distance)(nil), "protobuf.Distance")
	proto.RegisterType((*Detection)(nil), "protobuf.Detection")
}

func init() { proto.RegisterFile("protobuf/message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x6a, 0xdc, 0x30,
	0x10, 0xc6, 0xf1, 0x9f, 0xf5, 0xda, 0x93, 0x90, 0x16, 0x13, 0x52, 0x5d, 0x5a, 0x8c, 0x68, 0x61,
	0x4f, 0x5b, 0xe8, 0x25, 0x97, 0x9e, 0x4a, 0x48, 0xc9, 0x21, 0xa5, 0xb8, 0xc7, 0x1e, 0x8c, 0x62,
	0x8f, 0x17, 0x11, 0x5b, 0x32, 0x92, 0xb6, 0xb0, 0x2f, 0xd0, 0x27, 0xed, 0x83, 0x14, 0x8d, 0xe5,
	0x6c, 0x6f, 0xed, 0x96, 0xdc, 0xe6, 0xfb, 0x69, 0xf4, 0xcd, 0x68, 0x46, 0x70, 0x35, 0x19, 0xed,
	0xf4, 0xc3, 0xbe, 0x7f, 0x3f, 0xa2, 0xb5, 0x62, 0x87, 0x5b, 0x02, 0x65, 0xbe, 0x70, 0x7e, 0x0d,
	0xd9, 0x37, 0x39, 0x4e, 0x03, 0x96, 0xaf, 0x01, 0xf0, 0x07, 0x2a, 0xd7, 0x28, 0x31, 0x22, 0x8b,
	0xaa, 0x78, 0x53, 0xd4, 0x05, 0x91, 0x2f, 0x62, 0xc4, 0xf2, 0x02, 0x62, 0xd9, 0xb1, 0x98, 0x70,
	0x2c, 0x3b, 0xde, 0xc3, 0xfa, 0x16, 0x85, 0xdb, 0x9b, 0xbf, 0xde, 0xbc, 0x84, 0xd5, 0xce, 0xe8,
	0xfd, 0x14, 0x2e, 0xcf, 0x22, 0xf8, 0x25, 0x55, 0x34, 0xfb, 0x95, 0x57, 0x90, 0xb5, 0x5a, 0x9b,
	0xce, 0xb2, 0x94, 0x58, 0x50, 0xfc, 0x3b, 0x64, 0x5f, 0x07, 0x71, 0x40, 0x73, 0x62, 0x83, 0xe5,
	0x4b, 0x48, 0x06, 0xad, 0x58, 0x52, 0xc5, 0x9b, 0xa8, 0xf6, 0x21, 0x11, 0xe1, 0x58, 0x1a, 0x88,
	0x70, 0x5c, 0x40, 0xfe, 0x59, 0x8c, 0x78, 0xa7, 0x7a, 0x7d, 0xaa, 0x7d, 0x09, 0xe9, 0xce, 0x27,
	0x26, 0x44, 0x28, 0xf6, 0xcc, 0xe8, 0x01, 0xa9, 0x42, 0x51, 0x53, 0xcc, 0x7f, 0x46, 0x73, 0x8d,
	0x5a, 0xa8, 0xc7, 0xe7, 0xa8, 0x71, 0x0d, 0xe7, 0x13, 0xcd, 0xc3, 0x36, 0x46, 0xa8, 0x47, 0x96,
	0x56, 0xc9, 0xe6, 0xec, 0xc3, 0xe5, 0x76, 0xd9, 0xe8, 0x76, 0x9e, 0x96, 0x2f, 0x57, 0x9f, 0x85,
	0x4c, 0x2f, 0xf8, 0x47, 0x80, 0xe3, 0x91, 0x1f, 0xf7, 0x7c, 0x18, 0xba, 0x08, 0x8a, 0xb8, 0x96,
	0xca, 0x59, 0x6a, 0x63, 0x55, 0x07, 0xc5, 0xef, 0x21, 0xbf, 0x91, 0xd6, 0x09, 0xd5, 0xe2, 0x7f,
	0xbc, 0xa2, 0x93, 0xd6, 0x85, 0x4d, 0x50, 0xcc, 0x7f, 0x45, 0x50, 0xdc, 0xa0, 0xc3, 0xd6, 0x49,
	0xad, 0xfe, 0xcd, 0x30, 0x79, 0x32, 0x7c, 0x05, 0xeb, 0x1e, 0x85, 0x6b, 0x64, 0x17, 0x26, 0x9d,
	0x79, 0x79, 0xd7, 0x2d, 0x0b, 0x5e, 0x3d, 0x2d, 0x78, 0xf9, 0x04, 0xd9, 0xf1, 0x13, 0xbc, 0x83,
	0x17, 0x0a, 0x85, 0x69, 0x1e, 0x0e, 0xcd, 0x62, 0xb2, 0x26, 0x93, 0x73, 0x8f, 0x3f, 0x1d, 0x6e,
	0x67, 0xab, 0xb7, 0x70, 0xb1, 0xa4, 0x8d, 0xe8, 0xd0, 0x58, 0x96, 0x93, 0x47, 0xc8, 0xba, 0x27,
	0x56, 0xbe, 0x01, 0x90, 0xca, 0x47, 0xd8, 0x3a, 0xcb, 0x0a, 0xf2, 0xf9, 0x83, 0xfc, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x7e, 0x99, 0xa3, 0x4a, 0x80, 0x03, 0x00, 0x00,
}
