// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/message.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	protobuf/message.proto

It has these top-level messages:
	Simple
	Feature
	Player
	GameInfo
	GameRank
	PlayerRank
	Distance
	Detection
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Simple struct {
	EventName        *string `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Simple) Reset()                    { *m = Simple{} }
func (m *Simple) String() string            { return proto.CompactTextString(m) }
func (*Simple) ProtoMessage()               {}
func (*Simple) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Simple) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Simple) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type Feature struct {
	EventName        *string `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Group            *string `protobuf:"bytes,3,req,name=group" json:"group,omitempty"`
	Coords           *string `protobuf:"bytes,4,req,name=coords" json:"coords,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Feature) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Feature) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Feature) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *Feature) GetCoords() string {
	if m != nil && m.Coords != nil {
		return *m.Coords
	}
	return ""
}

type Player struct {
	EventName        *string  `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string  `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Lon              *float64 `protobuf:"fixed64,3,req,name=lon" json:"lon,omitempty"`
	Lat              *float64 `protobuf:"fixed64,4,req,name=lat" json:"lat,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Player) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Player) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Player) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func (m *Player) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

type GameInfo struct {
	EventName        *string `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Game             *string `protobuf:"bytes,3,req,name=game" json:"game,omitempty"`
	Role             *string `protobuf:"bytes,4,req,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameInfo) Reset()                    { *m = GameInfo{} }
func (m *GameInfo) String() string            { return proto.CompactTextString(m) }
func (*GameInfo) ProtoMessage()               {}
func (*GameInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GameInfo) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *GameInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *GameInfo) GetGame() string {
	if m != nil && m.Game != nil {
		return *m.Game
	}
	return ""
}

func (m *GameInfo) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

type GameRank struct {
	EventName        *string       `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string       `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Game             *string       `protobuf:"bytes,3,req,name=game" json:"game,omitempty"`
	PlayersRank      []*PlayerRank `protobuf:"bytes,4,rep,name=players_rank,json=playersRank" json:"players_rank,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GameRank) Reset()                    { *m = GameRank{} }
func (m *GameRank) String() string            { return proto.CompactTextString(m) }
func (*GameRank) ProtoMessage()               {}
func (*GameRank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GameRank) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *GameRank) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *GameRank) GetGame() string {
	if m != nil && m.Game != nil {
		return *m.Game
	}
	return ""
}

func (m *GameRank) GetPlayersRank() []*PlayerRank {
	if m != nil {
		return m.PlayersRank
	}
	return nil
}

type PlayerRank struct {
	Player           *string `protobuf:"bytes,1,req,name=player" json:"player,omitempty"`
	Points           *int32  `protobuf:"varint,2,req,name=points" json:"points,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerRank) Reset()                    { *m = PlayerRank{} }
func (m *PlayerRank) String() string            { return proto.CompactTextString(m) }
func (*PlayerRank) ProtoMessage()               {}
func (*PlayerRank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayerRank) GetPlayer() string {
	if m != nil && m.Player != nil {
		return *m.Player
	}
	return ""
}

func (m *PlayerRank) GetPoints() int32 {
	if m != nil && m.Points != nil {
		return *m.Points
	}
	return 0
}

type Distance struct {
	EventName        *string  `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string  `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Dist             *float64 `protobuf:"fixed64,3,req,name=dist" json:"dist,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Distance) Reset()                    { *m = Distance{} }
func (m *Distance) String() string            { return proto.CompactTextString(m) }
func (*Distance) ProtoMessage()               {}
func (*Distance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Distance) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Distance) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Distance) GetDist() float64 {
	if m != nil && m.Dist != nil {
		return *m.Dist
	}
	return 0
}

type Detection struct {
	EventName        *string  `protobuf:"bytes,1,req,name=event_name,json=eventName" json:"event_name,omitempty"`
	Id               *string  `protobuf:"bytes,3,req,name=id" json:"id,omitempty"`
	FeatId           *string  `protobuf:"bytes,4,req,name=feat_id,json=featId" json:"feat_id,omitempty"`
	Lat              *float64 `protobuf:"fixed64,5,req,name=lat" json:"lat,omitempty"`
	Lon              *float64 `protobuf:"fixed64,6,req,name=lon" json:"lon,omitempty"`
	NearByFeatId     *string  `protobuf:"bytes,7,req,name=near_by_feat_id,json=nearByFeatId" json:"near_by_feat_id,omitempty"`
	NearByMeters     *float64 `protobuf:"fixed64,8,req,name=near_by_meters,json=nearByMeters" json:"near_by_meters,omitempty"`
	Intersects       *string  `protobuf:"bytes,9,req,name=intersects" json:"intersects,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Detection) Reset()                    { *m = Detection{} }
func (m *Detection) String() string            { return proto.CompactTextString(m) }
func (*Detection) ProtoMessage()               {}
func (*Detection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Detection) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *Detection) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Detection) GetFeatId() string {
	if m != nil && m.FeatId != nil {
		return *m.FeatId
	}
	return ""
}

func (m *Detection) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Detection) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func (m *Detection) GetNearByFeatId() string {
	if m != nil && m.NearByFeatId != nil {
		return *m.NearByFeatId
	}
	return ""
}

func (m *Detection) GetNearByMeters() float64 {
	if m != nil && m.NearByMeters != nil {
		return *m.NearByMeters
	}
	return 0
}

func (m *Detection) GetIntersects() string {
	if m != nil && m.Intersects != nil {
		return *m.Intersects
	}
	return ""
}

func init() {
	proto.RegisterType((*Simple)(nil), "protobuf.Simple")
	proto.RegisterType((*Feature)(nil), "protobuf.Feature")
	proto.RegisterType((*Player)(nil), "protobuf.Player")
	proto.RegisterType((*GameInfo)(nil), "protobuf.GameInfo")
	proto.RegisterType((*GameRank)(nil), "protobuf.GameRank")
	proto.RegisterType((*PlayerRank)(nil), "protobuf.PlayerRank")
	proto.RegisterType((*Distance)(nil), "protobuf.Distance")
	proto.RegisterType((*Detection)(nil), "protobuf.Detection")
}

func init() { proto.RegisterFile("protobuf/message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0xcb, 0xd3, 0x40,
	0x10, 0xc6, 0x49, 0xd2, 0xa6, 0xc9, 0xbc, 0x2f, 0xaf, 0x12, 0x5e, 0x6a, 0x2e, 0x4a, 0x59, 0x14,
	0x7a, 0xaa, 0xe0, 0xa5, 0x17, 0x4f, 0x52, 0x2a, 0x3d, 0x54, 0x24, 0x1e, 0x3d, 0x84, 0x6d, 0x32,
	0x29, 0x4b, 0x93, 0xdd, 0xb0, 0xbb, 0x15, 0xfa, 0x05, 0xfc, 0xa4, 0x7e, 0x10, 0xd9, 0xc9, 0xa6,
	0xf5, 0x68, 0xc5, 0xdb, 0x3c, 0xbf, 0x4c, 0x9e, 0xd9, 0xf9, 0x03, 0xf3, 0x5e, 0x2b, 0xab, 0x0e,
	0xe7, 0xe6, 0x7d, 0x87, 0xc6, 0xf0, 0x23, 0xae, 0x08, 0x64, 0xc9, 0xc8, 0xd9, 0x1a, 0xe2, 0x6f,
	0xa2, 0xeb, 0x5b, 0xcc, 0x5e, 0x03, 0xe0, 0x0f, 0x94, 0xb6, 0x94, 0xbc, 0xc3, 0x3c, 0x58, 0x84,
	0xcb, 0xb4, 0x48, 0x89, 0x7c, 0xe1, 0x1d, 0x66, 0x4f, 0x10, 0x8a, 0x3a, 0x0f, 0x09, 0x87, 0xa2,
	0x66, 0x0d, 0xcc, 0xb6, 0xc8, 0xed, 0x59, 0xdf, 0xfb, 0x67, 0xf6, 0x0c, 0xd3, 0xa3, 0x56, 0xe7,
	0x3e, 0x8f, 0x08, 0x0d, 0x22, 0x9b, 0x43, 0x5c, 0x29, 0xa5, 0x6b, 0x93, 0x4f, 0x08, 0x7b, 0xc5,
	0xbe, 0x43, 0xfc, 0xb5, 0xe5, 0x17, 0xd4, 0xf7, 0x96, 0x79, 0x09, 0x51, 0xab, 0x24, 0x15, 0x09,
	0x0a, 0x17, 0x12, 0xe1, 0x96, 0xfc, 0x1d, 0xe1, 0x96, 0x71, 0x48, 0x3e, 0xf3, 0x0e, 0x77, 0xb2,
	0x51, 0xf7, 0xda, 0x67, 0x30, 0x39, 0xba, 0xc4, 0xa1, 0x09, 0x8a, 0x1d, 0xd3, 0xaa, 0x45, 0xdf,
	0x01, 0xc5, 0xec, 0x67, 0x30, 0xd4, 0x28, 0xb8, 0x3c, 0xfd, 0x8f, 0x1a, 0x6b, 0x78, 0xec, 0x69,
	0x1e, 0xa6, 0xd4, 0x5c, 0x9e, 0xf2, 0xc9, 0x22, 0x5a, 0x3e, 0x7c, 0x78, 0x5e, 0x8d, 0x1b, 0x5d,
	0x0d, 0xd3, 0x72, 0xe5, 0x8a, 0x07, 0x9f, 0xe9, 0x04, 0xfb, 0x08, 0x70, 0xfb, 0xe4, 0xc6, 0x3d,
	0x7c, 0xf4, 0xaf, 0xf0, 0x8a, 0xb8, 0x12, 0xd2, 0x1a, 0x7a, 0xc6, 0xb4, 0xf0, 0x8a, 0xed, 0x21,
	0xd9, 0x08, 0x63, 0xb9, 0xac, 0xf0, 0x1f, 0xba, 0xa8, 0x85, 0xb1, 0x7e, 0x13, 0x14, 0xb3, 0x5f,
	0x01, 0xa4, 0x1b, 0xb4, 0x58, 0x59, 0xa1, 0xe4, 0xdf, 0x19, 0x46, 0x57, 0xc3, 0x57, 0x30, 0x6b,
	0x90, 0xdb, 0x52, 0xd4, 0xe3, 0xad, 0x38, 0xb9, 0xab, 0xc7, 0x05, 0x4f, 0xaf, 0x0b, 0x1e, 0x8f,
	0x20, 0xbe, 0x1d, 0xc1, 0x3b, 0x78, 0x21, 0x91, 0xeb, 0xf2, 0x70, 0x29, 0x47, 0x93, 0x19, 0x99,
	0x3c, 0x3a, 0xfc, 0xe9, 0xb2, 0x1d, 0xac, 0xde, 0xc2, 0xd3, 0x98, 0xd6, 0xa1, 0x45, 0x6d, 0xf2,
	0x84, 0x3c, 0x7c, 0xd6, 0x9e, 0x58, 0xf6, 0x06, 0x40, 0x48, 0x17, 0x61, 0x65, 0x4d, 0x9e, 0x92,
	0xcf, 0x1f, 0xe4, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x3c, 0x85, 0xdc, 0x80, 0x03, 0x00,
	0x00,
}
