---
version: '3'
services:
    web:
        image: perenecabuto/catchcatch
        build: .
        ports:
            - "5050:5050"
        command:
            - "./server"
            - "-port"
            - "5050"
            - "-tile38-addr"
            - "tile38:9851"
            - "-influxdb-addr"
            - "http://influxdb:8086"
            - "-nats-addr"
            - "nats:4222"
            - "-workers-redis-addr"
            - "redis:6379"
        links:
            - nats
            - tile38
            - influxdb
        depends_on:
            - nats
            - tile38
            - influxdb
        networks:
            - traefik-net
            - internal            
        deploy:
            replicas: 3
            labels:
                - "traefik.port=5050"
                - "traefik.docker.network=traefik-net"
                - "traefik.frontend.rule=Host:catchcatch.local"

    tile38:
        image: tile38/tile38
        ports:
            - "9851:9851"
        networks:
            - internal

    nats:
        image: nats
        ports:
            - "4222:4222"
        networks:
            - internal

    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - internal

    influxdb:
        image: influxdb
        ports:
            - "8086:8086"
        networks:
            - internal

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        links:
            - influxdb
        networks:
            - internal
            - traefik-net
        deploy:
            labels:
                - "traefik.port=3000"
                - "traefik.docker.network=traefik-net"
                - "traefik.frontend.rule=Host:grafana.catchcatch.com"

    traefik:
        image: traefik
        command: --docker \
            --docker.swarmmode \
            --docker.domain=traefik \
            --docker.watch \
            --api
        networks:
            - traefik-net
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml

networks:
  traefik-net:
    external: true
  internal:
    external: false
