---
version: '3'
services:
    test:
        image: golang:1.11.1
        build: .
        volumes:
            - .:/go/src/github.com/perenecabuto/CatchCatch
        depends_on:
            - redis
            - nats
            - tile38
            - influxdb
        working_dir: /go/src/github.com/perenecabuto/CatchCatch
        environment:
            TILE38_ADDR: tile38:9851
        command: make test

    tile38:
        image: tile38/tile38
        ports:
        - "9851:9851"

    nats:
        image: nats
        ports:
        - "4222:4222"

    redis:
        image: redis:alpine
        ports:
        - "6379:6379"

    influxdb:
        image: influxdb:1.6-alpine
