---
version: '3'
services:
    web:
        image: perenecabuto/catchcatch
        build: .
        ports:
        - 5050:5050
        command:
        - "./server"
        - "-port"
        - "5050"
        - "-tile38-addr"
        - "tile38:9851"
        - "-influxdb-addr"
        - "http://influxdb:8086"
        - "-nats-addr"
        - "nats:4222"
        - "-workers-redis-addr"
        - "redis:6379"
        depends_on:
        - nats
        - tile38
        - influxdb
        networks:
        - internal
        environment:
        - VIRTUAL_HOST=localhost,catchcatch.local,catchcatch.ddns.net
        - VIRTUAL_PORT=5050
        - LETSENCRYPT_HOST=catchcatch.local,catchcatch.ddns.net
        - LETSENCRYPT_EMAIL=perenecabuto@gmail.com
        deploy:
            replicas: 3

    tile38:
        image: tile38/tile38
        ports:
        - "9851:9851"
        networks:
        - internal

    nats:
        image: nats
        ports:
        - "4222:4222"
        networks:
        - internal

    redis:
        image: redis
        ports:
        - "6379:6379"
        networks:
        - internal

    influxdb:
        image: influxdb
        ports:
        - "8086:8086"
        networks:
        - internal

    grafana:
        image: grafana/grafana
        ports:
        - "3000:3000"
        depends_on:
        - influxdb
        networks:
        - internal
        environment:
        - VIRTUAL_HOST=grafana.local,grafana.catchcatch.ddns.net
        - VIRTUAL_PORT=3000

    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        ports:
        - 80:80
        - 443:443
        networks:
        - public
        - internal
        volumes:
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "nginx_vhost:/etc/nginx/vhost.d"
        - "nginx_html:/usr/share/nginx/html"
        - "nginx_certs:/etc/nginx/certs"
        labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true

    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "nginx_vhost:/etc/nginx/vhost.d"
        - "nginx_html:/usr/share/nginx/html"
        - "nginx_certs:/etc/nginx/certs"

volumes:
    nginx_vhost:
    nginx_html:
    nginx_certs:


networks:
  public:
    external: true
  internal:
    external: false
