// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import time "time"
import worker "github.com/perenecabuto/CatchCatch/server/worker"

// TaskManagerQueue is an autogenerated mock type for the TaskManagerQueue type
type TaskManagerQueue struct {
	mock.Mock
}

// EnqueuePending provides a mock function with given fields: _a0
func (_m *TaskManagerQueue) EnqueuePending(_a0 *worker.Job) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*worker.Job) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnqueueToProcess provides a mock function with given fields: _a0
func (_m *TaskManagerQueue) EnqueueToProcess(_a0 *worker.Job) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*worker.Job) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Flush provides a mock function with given fields:
func (_m *TaskManagerQueue) Flush() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HeartbeatJob provides a mock function with given fields: job
func (_m *TaskManagerQueue) HeartbeatJob(job *worker.Job) error {
	ret := _m.Called(job)

	var r0 error
	if rf, ok := ret.Get(0).(func(*worker.Job) error); ok {
		r0 = rf(job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsJobOnProcessQueue provides a mock function with given fields: job
func (_m *TaskManagerQueue) IsJobOnProcessQueue(job *worker.Job) (bool, error) {
	ret := _m.Called(job)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*worker.Job) bool); ok {
		r0 = rf(job)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*worker.Job) error); ok {
		r1 = rf(job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JobsOnProcessQueue provides a mock function with given fields:
func (_m *TaskManagerQueue) JobsOnProcessQueue() ([]*worker.Job, error) {
	ret := _m.Called()

	var r0 []*worker.Job
	if rf, ok := ret.Get(0).(func() []*worker.Job); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*worker.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PollPending provides a mock function with given fields:
func (_m *TaskManagerQueue) PollPending() (*worker.Job, error) {
	ret := _m.Called()

	var r0 *worker.Job
	if rf, ok := ret.Get(0).(func() *worker.Job); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PollProcess provides a mock function with given fields: updatedUntil
func (_m *TaskManagerQueue) PollProcess(updatedUntil time.Time) (*worker.Job, error) {
	ret := _m.Called(updatedUntil)

	var r0 *worker.Job
	if rf, ok := ret.Get(0).(func(time.Time) *worker.Job); ok {
		r0 = rf(updatedUntil)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(updatedUntil)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveFromProcessingQueue provides a mock function with given fields: _a0
func (_m *TaskManagerQueue) RemoveFromProcessingQueue(_a0 *worker.Job) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*worker.Job) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetJobRunning provides a mock function with given fields: job, host, lockDuration
func (_m *TaskManagerQueue) SetJobRunning(job *worker.Job, host string, lockDuration time.Duration) (bool, error) {
	ret := _m.Called(job, host, lockDuration)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*worker.Job, string, time.Duration) bool); ok {
		r0 = rf(job, host, lockDuration)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*worker.Job, string, time.Duration) error); ok {
		r1 = rf(job, host, lockDuration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
