// Code generated by mockery v1.0.0
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import worker "github.com/perenecabuto/CatchCatch/server/worker"

// Task is an autogenerated mock type for the Task type
type Task struct {
	mock.Mock
}

// ID provides a mock function with given fields:
func (_m *Task) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Run provides a mock function with given fields: ctx, params
func (_m *Task) Run(ctx context.Context, params worker.TaskParams) error {
	ret := _m.Called(ctx, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, worker.TaskParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
