// Code generated by mockery v1.0.0
package websocket

import context "context"
import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MockWSDriver is an autogenerated mock type for the WSDriver type
type MockWSDriver struct {
	mock.Mock
}

// Handler provides a mock function with given fields: ctx, onConnect
func (_m *MockWSDriver) Handler(ctx context.Context, onConnect func(context.Context, WSConnection)) http.Handler {
	ret := _m.Called(ctx, onConnect)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, WSConnection)) http.Handler); ok {
		r0 = rf(ctx, onConnect)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}
