// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import websocket "github.com/perenecabuto/CatchCatch/server/websocket"

// Authenticator is an autogenerated mock type for the Authenticator type
type Authenticator struct {
	mock.Mock
}

// GetConnectionID provides a mock function with given fields: _a0
func (_m *Authenticator) GetConnectionID(_a0 websocket.WSConnection) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(websocket.WSConnection) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(websocket.WSConnection) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
