// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// WSConnection is an autogenerated mock type for the WSConnection type
type WSConnection struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *WSConnection) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: _a0
func (_m *WSConnection) Read(_a0 *[]byte) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(*[]byte) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*[]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Send provides a mock function with given fields: payload
func (_m *WSConnection) Send(payload []byte) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
