// Code generated by mockery v1.0.0
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import websocket "github.com/perenecabuto/CatchCatch/server/websocket"

// WSEventHandler is an autogenerated mock type for the WSEventHandler type
type WSEventHandler struct {
	mock.Mock
}

// OnConnection provides a mock function with given fields: _a0, _a1
func (_m *WSEventHandler) OnConnection(_a0 context.Context, _a1 *websocket.WSConnectionHandler) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *websocket.WSConnectionHandler) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnStart provides a mock function with given fields: _a0, _a1
func (_m *WSEventHandler) OnStart(_a0 context.Context, _a1 *websocket.WSServer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *websocket.WSServer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
