// Code generated by mockery v1.0.0
package mocks

import metrics "github.com/perenecabuto/CatchCatch/server/metrics"
import mock "github.com/stretchr/testify/mock"

// Collector is an autogenerated mock type for the Collector type
type Collector struct {
	mock.Mock
}

// Notify provides a mock function with given fields: measurement, tags, values
func (_m *Collector) Notify(measurement string, tags metrics.Tags, values metrics.Values) error {
	ret := _m.Called(measurement, tags, values)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, metrics.Tags, metrics.Values) error); ok {
		r0 = rf(measurement, tags, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Ping provides a mock function with given fields:
func (_m *Collector) Ping() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RunGlobalCollector provides a mock function with given fields:
func (_m *Collector) RunGlobalCollector() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
