// Code generated by mockery v1.0.0
package mocks

import context "context"
import game "github.com/perenecabuto/CatchCatch/server/game"
import mock "github.com/stretchr/testify/mock"
import model "github.com/perenecabuto/CatchCatch/server/model"
import service "github.com/perenecabuto/CatchCatch/server/service"

// GameService is an autogenerated mock type for the GameService type
type GameService struct {
	mock.Mock
}

// Create provides a mock function with given fields: gameID
func (_m *GameService) Create(gameID string) (*game.Game, error) {
	ret := _m.Called(gameID)

	var r0 *game.Game
	if rf, ok := ret.Get(0).(func(string) *game.Game); ok {
		r0 = rf(gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*game.Game)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameByID provides a mock function with given fields: gameID
func (_m *GameService) GameByID(gameID string) (*game.Game, *game.Event, error) {
	ret := _m.Called(gameID)

	var r0 *game.Game
	if rf, ok := ret.Get(0).(func(string) *game.Game); ok {
		r0 = rf(gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*game.Game)
		}
	}

	var r1 *game.Event
	if rf, ok := ret.Get(1).(func(string) *game.Event); ok {
		r1 = rf(gameID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*game.Event)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(gameID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GamesAround provides a mock function with given fields: p
func (_m *GameService) GamesAround(p model.Player) ([]service.GameWithCoords, error) {
	ret := _m.Called(p)

	var r0 []service.GameWithCoords
	if rf, ok := ret.Get(0).(func(model.Player) []service.GameWithCoords); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.GameWithCoords)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Player) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObserveGamePlayers provides a mock function with given fields: ctx, gameID, callback
func (_m *GameService) ObserveGamePlayers(ctx context.Context, gameID string, callback func(model.Player, bool) error) error {
	ret := _m.Called(ctx, gameID, callback)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(model.Player, bool) error) error); ok {
		r0 = rf(ctx, gameID, callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObserveGamesEvents provides a mock function with given fields: ctx, callback
func (_m *GameService) ObserveGamesEvents(ctx context.Context, callback func(*game.Game, game.Event) error) error {
	ret := _m.Called(ctx, callback)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(*game.Game, game.Event) error) error); ok {
		r0 = rf(ctx, callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: gameID
func (_m *GameService) Remove(gameID string) error {
	ret := _m.Called(gameID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(gameID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: g, evt
func (_m *GameService) Update(g *game.Game, evt game.Event) error {
	ret := _m.Called(g, evt)

	var r0 error
	if rf, ok := ret.Get(0).(func(*game.Game, game.Event) error); ok {
		r0 = rf(g, evt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
