// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Message is an autogenerated mock type for the Message type
type Message struct {
	mock.Mock
}

// GetEventName provides a mock function with given fields:
func (_m *Message) GetEventName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ProtoMessage provides a mock function with given fields:
func (_m *Message) ProtoMessage() {
	_m.Called()
}

// Reset provides a mock function with given fields:
func (_m *Message) Reset() {
	_m.Called()
}

// String provides a mock function with given fields:
func (_m *Message) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
