// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/perenecabuto/CatchCatch/server/model"

// PlayerLocationService is an autogenerated mock type for the PlayerLocationService type
type PlayerLocationService struct {
	mock.Mock
}

// All provides a mock function with given fields:
func (_m *PlayerLocationService) All() (model.PlayerList, error) {
	ret := _m.Called()

	var r0 model.PlayerList
	if rf, ok := ret.Get(0).(func() model.PlayerList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.PlayerList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: p
func (_m *PlayerLocationService) Remove(p *model.Player) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Player) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: p
func (_m *PlayerLocationService) Set(p *model.Player) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Player) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
