// Code generated by mockery v1.0.0
package mocks

import context "context"
import http "net/http"
import mock "github.com/stretchr/testify/mock"
import websocket "github.com/perenecabuto/CatchCatch/server/websocket"

// WSDriver is an autogenerated mock type for the WSDriver type
type WSDriver struct {
	mock.Mock
}

// HTTPHandler provides a mock function with given fields: ctx, onConnect
func (_m *WSDriver) HTTPHandler(ctx context.Context, onConnect func(context.Context, websocket.WSConnection)) http.Handler {
	ret := _m.Called(ctx, onConnect)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, websocket.WSConnection)) http.Handler); ok {
		r0 = rf(ctx, onConnect)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}
